#!/bin/bash
set -e -x

SCRIPT_DIR=$(dirname $0)
VERSION_DIR="$SCRIPT_DIR/gh-pages/version/$1"
BUILD_DIR="$SCRIPT_DIR/build"
VERSION_FILE="$SCRIPT_DIR/source/versionfile"

if [[ $# -eq 0 ]]; then
  echo "You need to provide the version number as the first argument"
  exit 0
fi

if [[ -d $VERSION_DIR ]]; then
  echo "That version already exists."
  exit 1
fi

echo $1 > $VERSION_FILE

bundle exec middleman build

rm $VERSION_FILE

ls $SCRIPT_DIR/gh-pages | grep -v version | xargs rm -rf

mkdir -p $VERSION_DIR

cp -R $BUILD_DIR/ $SCRIPT_DIR/gh-pages/
cp -R $BUILD_DIR/ $VERSION_DIR/
