#!/bin/bash
set -e -x

if [[ $# -eq 0 ]] ; then
  echo "You need to provide the version number as the first argument"
  exit 0
fi

middleman build

aws s3 sync build s3://cloudcontroller-api-docs/$1 --acl public-read

aws s3 rm s3://cloudcontroller-api-docs/release-candidate/ --recursive
aws s3 cp s3://cloudcontroller-api-docs/$1/ s3://cloudcontroller-api-docs/release-candidate/ --recursive
